### ISSUE TITLE
EGradle IDE: Error markers not deleted

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#148]
Appeared inside build.gradle in virtual root project.

Changed multiproject example, changed current() to currentx() run, error marker appeared, but delete of former error marker did not work. **I did delete a marker manually in error view** - maybe this forced the problem, because the error was still listed in ArrayList...

Marker id 397 not found. did always appear. It seems the marker list is not updated when a marker is no more found - so it remains all time until eclipse restart!

**Comment by de-jcup** [comment]
``
org.eclipse.core.internal.resources.ResourceException: Marker id 397 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:58)
	at org.eclipse.core.internal.resources.Marker.getType(Marker.java:209)
	at de.jcup.egradle.eclipse.ui.UnpersistedMarkerHelper.removeAllRegisteredMarkers(UnpersistedMarkerHelper.java:59)
	at de.jcup.egradle.eclipse.api.EGradleUtil.removeAllValidationErrorsOfConsoleOutput(EGradleUtil.java:611)
	at de.jcup.egradle.eclipse.console.EGradleConsoleLineTracker.init(EGradleConsoleLineTracker.java:39)
	at org.eclipse.debug.internal.ui.views.console.ConsoleLineNotifier.connect(ConsoleLineNotifier.java:56)
	at org.eclipse.ui.internal.console.ConsolePatternMatcher.addPatternMatchListener(ConsolePatternMatcher.java:232)
	at org.eclipse.ui.console.TextConsole.addPatternMatchListener(TextConsole.java:409)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole.<init>(ProcessConsole.java:228)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsoleManager.launchChanged(ProcessConsoleManager.java:149)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.run(LaunchManager.java:453)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.notify(LaunchManager.java:433)
	at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1043)
	at org.eclipse.debug.core.Launch.fireChanged(Launch.java:393)
	at org.eclipse.debug.core.Launch.addProcess(Launch.java:355)
	at org.eclipse.debug.core.model.RuntimeProcess.<init>(RuntimeProcess.java:126)
	at de.jcup.egradle.eclipse.launch.EGradleRuntimeProcess.<init>(EGradleRuntimeProcess.java:31)
	at de.jcup.egradle.eclipse.launch.EGradleRuntimeProcess.create(EGradleRuntimeProcess.java:48)
	at de.jcup.egradle.eclipse.execution.EclipseLaunchProcessExecutor.handleProcessStarted(EclipseLaunchProcessExecutor.java:115)
	at de.jcup.egradle.core.process.SimpleProcessExecutor.execute(SimpleProcessExecutor.java:97)
	at de.jcup.egradle.eclipse.execution.EclipseLaunchProcessExecutor.execute(EclipseLaunchProcessExecutor.java:57)
	at de.jcup.egradle.core.GradleExecutor.execute(GradleExecutor.java:63)
	at de.jcup.egradle.eclipse.execution.GradleExecutionDelegate.execute(GradleExecutionDelegate.java:173)
	at de.jcup.egradle.eclipse.execution.GradleJob.run(GradleJob.java:40)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
``
