### ISSUE TITLE
Error on opening Preferences/General/Keys after installing EGradle

### ISSUE THREAD

**Issue by dpGoose** [de-jcup/egradle#150]
After installing EGradle going into Preferences/General/Keys throws up the following error:

An error has occurred. See error log for more details.
org.eclipse.debug.core.Launch cannot be cast to java.lang.String

It didn't happen the first time I went into keys. I suspect it is after I made a change and saved. This happens on three separate Windows 10 installations. Uninstalling Egradle stops the error occurring.

Neon.1a Release(4.6.1), Build id: 20161007-1200
EGradle 1.0.2

**Comment by de-jcup** [comment]
@dpGoose  .Could you please append the full trace from error log view?

**Comment by dpGoose** [comment]
Some more observations. I have an EGradle task set up to run using the Run command on the toolbar. The error will show only after I click run a task and then open the keys preferences. I can access keys without any problems after Eclipse is started but before running a task.

I have tried removing EGradle and adding a normal Java Application run configuration and this doesn't cause the problem.

I'm not familiar enough with the Eclipse architecture to investigate it much further but am willing to run any tests required.

Here's the log. I can't see anything directly mentioning EGradle but it did only start happening after it was installed.

`java.lang.ClassCastException: org.eclipse.debug.core.Launch cannot be cast to java.lang.String
	at org.eclipse.core.commands.ParameterizedCommand.expandParameters(ParameterizedCommand.java:182)
	at org.eclipse.core.commands.ParameterizedCommand.generateCombinations(ParameterizedCommand.java:259)
	at org.eclipse.ui.internal.keys.model.BindingModel.init(BindingModel.java:178)
	at org.eclipse.ui.internal.keys.model.KeyController.init(KeyController.java:125)
	at org.eclipse.ui.internal.keys.NewKeysPreferencePage.init(NewKeysPreferencePage.java:1187)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceNode.createPage(WorkbenchPreferenceNode.java:58)
	at org.eclipse.jface.preference.PreferenceDialog.createPage(PreferenceDialog.java:1280)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.createPage(FilteredPreferenceDialog.java:355)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1167)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:608)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:656)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:653)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:878)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:875)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1244)
	at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1270)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
	at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:431)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)`

**Comment by de-jcup** [comment]
Ok thanks. I will test it too. Maybe i am able to fix it with 1.1.0 release

**Comment by de-jcup** [comment]
Problem is reproducable and **not OS specific**

How to reproduce:
- Create a launch configuration without project, as task use "tasks"
- Run launch configuration
- After this open Preferences "General->Keys"
- Exception ocurs

**_Remark:_**
- _The problem stays after execution_
- _No save operations on preferences necessary_
- _After an eclipse restart the error does not occur as long as no launch configuration is executed. Also a quick launch does not produce the problem._

**Comment by de-jcup** [comment]
Will be fixed with 1.1.0

**Comment by de-jcup** [comment]
@dpGoose : I fixed the issue. It will be part of upcoming Release 1.1.0 which will come the next days (maybe friday)

**Comment by de-jcup** [comment]
@dpGoose I just release version 1.1.3 at eclipse market place. This version contains the bugfix :-)

**Comment by dpGoose** [comment]
@de-jcup That's great. I have installed and it is now okay. Thank you.
