### ISSUE TITLE
Reimporting projects does not restore the team provider shares

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/egradle#310]
When projects are shared (e.g. GIT ) and a full reimport is triggered the projects must be shared again to the team providers manually. This is very inconvenient.

If it's possible this should be automated

**Comment by de-jcup** [comment]
https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fteam%2Fcore%2FRepositoryProvider.html

There are static methods which could do the job:

isShared(project);
getRepositoryProvider(project);
setProject(project) + configureProject()

**Comment by de-jcup** [comment]
The code changes in branch have to be tested with big enterprise project where reimport did NOT reconnect to team providers. When using simple project setups the team provider do auto connect without usage of project share support.

It must be checked if the problem exists and if its fixed by the new introduced class + usage...

**Comment by de-jcup** [comment]
Hmm... got problems with last commit on testing on big project:

```
java.io.FileNotFoundException: C:\dev\workspaces\bigproject-neon\.metadata\.plugins\org.eclipse.core.resources\.projects\rest-ws-test-mock\org.eclipse.egit.core\GitProjectData.properties (Das System kann die angegebene Datei nicht finden)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.egit.core.project.GitProjectData.load(GitProjectData.java:613)
	at org.eclipse.egit.core.project.GitProjectData.get(GitProjectData.java:218)
	at org.eclipse.egit.core.GitProvider.getData(GitProvider.java:106)
	at org.eclipse.egit.core.project.RepositoryMapping.getProjectData(RepositoryMapping.java:361)
	at org.eclipse.egit.core.project.RepositoryMapping.findMapping(RepositoryMapping.java:377)
	at org.eclipse.egit.core.project.RepositoryMapping.getMapping(RepositoryMapping.java:317)
	at org.eclipse.egit.core.internal.util.ResourceUtil.getRepository(ResourceUtil.java:702)
	at org.eclipse.egit.ui.internal.resources.ResourceStateFactory.getIndexDiffDataOrNull(ResourceStateFactory.java:89)

```

**Comment by de-jcup** [comment]
I found the reason for the behaviour at all:

It looks a like that the reimport process which do delete former projects information delete the gitProvider information - when long running (many project data to delete/to import) the team provider information get lost.
