### ISSUE TITLE
Error when installing egradle from the market place

### ISSUE THREAD

**Issue by wolfgang-ch** [de-jcup/egradle#388]
This message is displayed 

![image](https://user-images.githubusercontent.com/1283445/145584740-1f2eb7ae-b323-4b72-81ee-4e02e5dfb2e3.png)

```
eclipse.buildId=4.22.0.I20211124-1800
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_UK
Framework arguments:  -xxxclean -xxxdebug -xxxconsolelog -xxxvm C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-openj9\bin\java.exe
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/DAT/ws-MT-422/ -xxxclean -xxxdebug -xxxconsolelog -xxxvm C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-openj9\bin\java.exe

org.eclipse.equinox.p2.transport.ecf
Error
Fri Dec 10 14:55:15 CET 2021
Unable to read repository at https://de-jcup.github.io/update-site-egradle/update-site/content.xml.

org.eclipse.core.runtime.CoreException: Transport initialization error.
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.fromExceptionMessage(RepositoryStatusHelper.java:109)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.fromMessage(RepositoryStatusHelper.java:105)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileInfoReader.sendBrowseRequest(FileInfoReader.java:166)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileInfoReader.getRemoteFiles(FileInfoReader.java:109)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileInfoReader.getRemoteFile(FileInfoReader.java:125)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileInfoReader.getLastModified(FileInfoReader.java:130)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.getLastModified(RepositoryTransport.java:249)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.getLastModified(CacheManager.java:283)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:231)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:69)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:89)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:63)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:685)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.epp.internal.mpc.ui.operations.AbstractProvisioningOperation.addRepositories(AbstractProvisioningOperation.java:94)
	at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.computeInstallableUnits(ProfileChangeOperationComputer.java:374)
	at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.run(ProfileChangeOperationComputer.java:168)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```

**Comment by de-jcup** [comment]
Hello, I just installed eclipse 2021-12 fresh and installed then EGradle 2.8.0 from eclipse marketplace - using also Java 11 (but a newer version than yours). 

Worked without any problems! Maybe you just try it again?

**Comment by wolfgang-ch** [comment]
The installation of Egradle 2.8.0 worked now also in my IDE :-)
