### ISSUE TITLE
Error while opening Help

### ISSUE THREAD

**Issue by nlisker** [de-jcup/egradle#424]
Pressing F1 to open Help in Eclipse causes:

```
Parse error occurred while adding document /de.jcup.egradle.eclipse.plugin.main/html/user_guide/junit-integration.html to search index C:\Dev\Minimal 4.33\configuration\org.eclipse.help.base\index\en_US.

org.apache.lucene.demo.html.ParseException: Encountered "\"" at line 66, column 37.
Was expecting one of:
    <ArgName> ...
    <TagEnd> ...
    
	at org.apache.lucene.demo.html.HTMLParser.generateParseException(HTMLParser.java:694)
	at org.apache.lucene.demo.html.HTMLParser.jj_consume_token(HTMLParser.java:575)
	at org.apache.lucene.demo.html.HTMLParser.Tag(HTMLParser.java:299)
	at org.apache.lucene.demo.html.HTMLParser.HTMLDocument(HTMLParser.java:192)
	at org.apache.lucene.demo.html.HTMLParser.parse(HTMLParser.java:95)
	at org.eclipse.help.internal.search.HTMLDocParser.openDocument(HTMLDocParser.java:92)
	at org.eclipse.help.internal.search.HTMLSearchParticipant.addDocument(HTMLSearchParticipant.java:64)
	at org.eclipse.help.internal.search.SearchIndex.addDocument(SearchIndex.java:264)
	at org.eclipse.help.internal.search.IndexingOperation.addDocuments(IndexingOperation.java:248)
	at org.eclipse.help.internal.search.IndexingOperation.addNewDocuments(IndexingOperation.java:159)
	at org.eclipse.help.internal.search.IndexingOperation.execute(IndexingOperation.java:108)
	at org.eclipse.help.internal.search.LocalSearchManager.updateIndex(LocalSearchManager.java:622)
	at org.eclipse.help.internal.search.LocalSearchManager.ensureIndexUpdated(LocalSearchManager.java:596)
	at org.eclipse.help.internal.search.federated.IndexerJob.run(IndexerJob.java:35)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

eclipse.buildId=4.33.0.I20240903-0240
java.version=21.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

**Comment by de-jcup** [comment]
I was not able to reproduce this with Eclipse 4.33.

I opened EGradle help (embedded + own window), looked at every page. No problems
I searched in help for EGradle parts.. Same: No problems.

To help or to fix anything, I need a way to reproduce this

**Comment by nlisker** [comment]
After updating various things like the Java version, some Eclipse components and EGradle, I can't reproduce this either. Help opens correctly.

Closing.
